### ISSUE TITLE
Optional SecurityDefinitions could use default

### ISSUE THREAD

**Issue by entropi** [mavwolverine/fastapi_swagger2#2]
https://github.com/virajkanwade/fastapi_swagger2/blob/fastapi_0.100.0/src/fastapi_swagger2/models.py#L330

I think `securityDefinitions: Optional[Dict[str, Union[SecurityScheme, Reference]]]` could use a default of ` = None` to avoid pydantic validation errors when not present.

**Comment by mavwolverine** [comment]
Thanks @entropi will take a look.

**Comment by mavwolverine** [comment]
https://pypi.org/project/fastapi_swagger2/0.2.3/

**Comment by mavwolverine** [comment]
Thanks @entropi

**Comment by entropi** [comment]
Thank you for the quick merge and packaging!

**Comment by mavwolverine** [comment]
@entropi Chad, unfortunately the project I was working on is scrapped. So I am currently not actively working on this. If you are still actively using it and find any issues, do let me know. Happy to continue maintaining the project.
Thanks
